# basic
algorithm_name: "goal-dqn"
env_id: "four-room-v0"
runs_name: "four-room"
goal_conditioned: true
her: false

# cuda
gpu_id: 0

# seed
seed: 1

# env
random_goal: false
random_start: false

# training settings
minibatch_size: 64
lr: 1.0e-3  # Adam optimizer settings
update_frequency: 1  # update model for every n transition collected
target_update_frequency: 100
discount_factor: 0.99
timesteps: 15000 #100000 

# replay buffer settings
replay_start_size: 1000
replay_buffer_size: 10000 #1000000

# explicit exploration
initial_exploration: 1.
final_exploration: 0.
final_exploration_step: 10000
test_exploration: 0.001  # The exploration rate of the test Agent
